version: '3'
services:

  frontend:
    container_name: agung2001.github.io_frontend
    image: agung2001/agung2001.github.io:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./src:/app/src
      - ./static:/app/static
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    ports:
      - ${FRONTEND_PORT-80}:3000

  backend:
    container_name: agung2001.github.io_backend
    image: alpine:latest
    restart: always
    volumes:
      - ./bin:/app/bin
    command: [ "/app/bin/cakrawala", "--api", "--run", "--port", "3000" ]
    ports:
      - ${BACKEND_PORT-81}:3000
