# Use Node.js 16 as the base image
FROM node:16

# Set the working directory to /app
WORKDIR /app
COPY . .

# Build the application
RUN npm i --force
# RUN npx grunt

# Expose the default SvelteKit port
EXPOSE 3000
