version: '3'
services:

  webserver:
    container_name: agung2001.github.io
    image: agung2001/agung2001.github.io:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./src:/app/src
      - ./static:/app/static
    command: ["yarn", "dev", "--host", "0.0.0.0"]
    ports:
      - ${WEBSERVER_PORT-80}:3000
