version: '3'
services:

  webserver:
    container_name: agung2001.github.io
    image: agung2001/agung2001.github.io:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    working_dir: /app
    volumes:
      - ${PWD}/src:/app/src
      - ${PWD}/static:/app/static
      - ${PWD}/vaults:/app/vaults
    command: "yarn serve"
    ports:
      - ${FRONTEND_PORT-80}:3000
      - ${BACKEND_PORT-81}:${BACKEND_PORT-81}
    networks:
      - agung2001.github.io

networks:
    agung2001.github.io:
