version: '3'
services:

  frontend:
    container_name: agung2001.github.io_frontend
    image: agung2001/agung2001.github.io:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    working_dir: /app
    volumes:
      - ${PWD}/src:/app/src
      - ${PWD}/static:/app/static
    command: ["yarn", "serve"]
    ports:
      - ${FRONTEND_PORT-80}:3000
      - ${BACKEND_PORT-81}:3001
    networks:
      - agung2001.github.io

  redis:
    image: redis
    container_name: agung2001.github.io_redis
    restart: always
    ports:
      - ${REDIS_PORT-6379}:6379
    volumes:
      - ${PWD}/data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - agung2001.github.io

networks:
    agung2001.github.io:
