export default [
	{
		"label": "💰 Financial Contribution",
		"description": "Help support community by making a financial contribution.",
		"buttons": [
			{
				"label": "Asciidoctor",
				"caption": "user-friendly publishing toolchain for converting AsciiDoc",
				"link": "https://opencollective.com/asciidoctor",
				"icon": "fas fa-circle-notch",
				"color": "#0069b2",
				"platform": "Open Collective",
				"amount": "$1/month",
			},
			{
				"label": "Open Broadcaster Software (OBS)",
				"caption": "Free and open source software for video recording and live streaming",
				"link": "https://opencollective.com/opensid",
				"icon": "fas fa-circle-notch",
				"color": "#0069b2",
				"platform": "Open Collective",
				"amount": "$1/month",
			},
			{
				"label": "Open Collective",
				"caption": "Funding platform for open source projects",
				"link": "https://opencollective.com/opencollective",
				"icon": "fas fa-circle-notch",
				"color": "#0069b2",
				"platform": "Open Collective",
				"amount": "$1/month",
			},
			{
				"label": "OpenSID",
				"caption": "Open Source Information System for Government",
				"link": "https://opencollective.com/opensid",
				"icon": "fas fa-circle-notch",
				"color": "#0069b2",
				"platform": "Open Collective",
				"amount": "$1/month",
			},
			{
				"label": "Programmer Zaman Now",
				"caption": "Programming Tutorial in Bahasa Indonesia",
				"link": "https://www.youtube.com/@ProgrammerZamanNow",
				"icon": "fab fa-youtube",
				"color": "#ff0000",
				"platform": "YouTube",
				"amount": "IDR 4.9K/month",
			},
			{
				"label": "Svelte",
				"caption": "Cybernetically enhanced web apps",
				"link": "https://opencollective.com/svelte",
				"icon": "fas fa-circle-notch",
				"color": "#0069b2",
				"platform": "Open Collective",
				"amount": "$1/month",
			},
			{
				"label": "Syncthing",
				"caption": "Open Source File Synchronization",
				"link": "https://github.com/syncthing",
				"icon": "fab fa-github",
				"color": "#24292f",
				"platform": "GitHub Sponsor",
				"amount": "$1/month",
			},
			{
				"label": "UAParser.js",
				"caption": "JS library to detect user's agent",
				"link": "https://opencollective.com/ua-parser-js",
				"icon": "fas fa-circle-notch",
				"color": "#0069b2",
				"platform": "Open Collective",
				"amount": "$1/month",
			},
		]
	},
	{
		"label": "🎮 Code Contribution",
		"description": "Help support open source project by making a code contribution.",
		"badges": [
			{
				"label": "ISSUE:OPEN",
				"link": "https://github.com/search?q=is%3Aissue+is%3Aopen+author%3Aagung2001+&type=issues",
				"color": "#2ecc71",
			},
			{
				"label": "ISSUE:CLOSED",
				"link": "https://github.com/search?q=is%3Aissue+is%3Aclosed+author%3Aagung2001+&type=issues",
				"color": "#2ecc71",
			},
			{
				"label": "PR:OPEN",
				"link": "https://github.com/search?q=is%3Apr+is%3Aopen+author%3Aagung2001+&type=pullrequests",
				"color": "#3498db",
			},
			{
				"label": "PR:CLOSE",
				"link": "https://github.com/search?q=is%3Apr+is%3Aclosed+author%3Aagung2001+&type=pullrequests",
				"color": "#3498db",
			}
		],
		"buttons_featured": [
			{
				"label": "Github - woocommerce/woocommerce-blocks",
				"caption": "WooCommerce Blocks for the new editor",
				"link": "https://github.com/woocommerce/woocommerce-blocks/pull/11932",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@29a0d57fac53f02cd53155f90378bf1b0e52fb1e/static/repo/woocommerce-woocommerce-blocks-11932.jpg",
			},
			{
				"label": "GitHub - phpDocumentor/phpDocumentor",
				"caption": "Documentation Generator for PHP",
				"link": "https://github.com/phpDocumentor/phpDocumentor/pull/3796",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@a9225482798a949d7cf6a32540d8d135d3bfc0c0/static/repo/phpDocumentor-phpDocumentor-3796.jpg",
			},
			{
				"label": "GitHub - redis/node-redis",
				"caption": "Redis client for Node.js",
				"link": "https://github.com/redis/node-redis/pull/2357",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@29a0d57fac53f02cd53155f90378bf1b0e52fb1e/static/repo/redis-node-redis-2357.jpg",
			},
			{
				"label": "GitHub - agung2001/agung2001.github.io",
				"caption": "Personal Website Repository",
				"link": "https://github.com/agung2001/agung2001.github.io/pull/1",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@29a0d57fac53f02cd53155f90378bf1b0e52fb1e/static/repo/agung2001-agung2001.github.io-1.jpg",
			},
		],
		"buttons": [
			{
				"label": "GitHub - artistudioxyz/aspri",
				"caption": "ASPRI Asisten Pribadi Koleksi Script-Library",
				"link": "https://github.com/artistudioxyz/aspri/pull/9",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@f03596feba7a10113046a51ba52176183e71d54e/static/repo/artistudioxyz-aspri-9.jpg",
			},
			{
				"label": "GitHub - artistudioxyz/aspri",
				"caption": "ASPRI Asisten Pribadi Koleksi Script-Library",
				"link": "https://github.com/artistudioxyz/aspri/pull/6",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@f03596feba7a10113046a51ba52176183e71d54e/static/repo/artistudioxyz-aspri-6.jpg",
			},
			{
				"label": "GitHub - dimaszulfa/Programmer-Cheatsheet",
				"caption": "Programmer Cheatsheet Repository",
				"link": "https://github.com/dimaszulfa/Programmer-Cheatsheet/pull/3",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@60043fdcf7c9e2f2fce8ec2a2c1f091fbf1baddc/static/repo/dimaszulfa-Programmer-Cheatsheet-3.jpg",
			},
			{
				"label": "GitHub - kamikerjaremote/kamikerjaremote.github.io",
				"caption": "Kami Kerja Remote Website Repository",
				"link": "https://github.com/kamikerjaremote/kamikerjaremote.github.io/pull/1",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@65e35dec045d2e148f2878116115a44cc715470c/static/repo/kamikerjaremote-kamikerjaremote.github.io-1.jpg",
			},
			{
				"label": "GitHub - OpenSID/OpenSID",
				"caption": "Open Source Information System for Government",
				"link": "https://github.com/OpenSID/OpenSID/pull/8584",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@d105ff3e4ff451271c03266d2b68ec9cc3e94400/static/repo/OpenSID-OpenSID-8584.jpg",
			},
			{
				"label": "GitHub - Scattercatt/Slippi-stats",
				"caption": "Slippi Stats for Super Smash Bros. Melee",
				"link": "https://github.com/Scattercatt/Slippi-stats/pull/8",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@29a0d57fac53f02cd53155f90378bf1b0e52fb1e/static/repo/Scattercatt-Slippi-stats-8.jpg",
			},
			{
				"label": "GitHub - VectorChi/worldpresidents",
				"caption": "World Presidents Database",
				"link": "https://github.com/VectorChi/worldpresidents/pull/55",
				"type": "opengraph",
				"src": "https://cdn.jsdelivr.net/gh/agung2001/agung2001.github.io@29a0d57fac53f02cd53155f90378bf1b0e52fb1e/static/repo/VectorChi-worldpresidents-55.jpg",
			},
		]
	},
]
